<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationManifest></ApplicationManifest>

		<!-- VERSIONING -->
		<Version>1.0.0-preview.5</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0-preview.5</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		
		<!-- BRANDING -->
		<AssemblyTitle>Windows Performance Optimizer</AssemblyTitle>
		<Product>WinBoost Pro 11</Product>
		<Company>WinBoost</Company>
		<Description>Windows Performance Optimizer</Description>
		<Copyright>© 2026 WinBoost. All rights reserved.</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\Flags\gb.png" />
		<None Remove="Assets\Flags\ro.png" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="browser-extension\safe-click\icons\" />
		<Folder Include="Resources\" />
		<Folder Include="Services\Services\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
		<PackageReference Include="LiteDB" Version="5.0.21" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
		
		<PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WinBoost.UpdateWorker\WinBoost.UpdateWorker.csproj" />
		<ProjectReference Include="..\WinBoost.RecoveryWorker\WinBoost.RecoveryWorker.csproj" />
		<ProjectReference Include="..\WinBoost.SelfUpdateWorker\WinBoost.SelfUpdateWorker.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Resource Include="Assets\Flags\gb.png" />
		<Resource Include="Assets\Flags\ro.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="ViewModels\DashboardViewModel.cs">
			<Generator>MSBuild:Compile</Generator>
		</Compile>

		<Compile Update="ViewModels\WindowsUpdateViewModel.cs">
			<Generator>MSBuild:Compile</Generator>
		</Compile>
	</ItemGroup>

</Project>